wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1711721251.0
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 23
      4: 3.10.11
      5: 0.16.5
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
